version: "3.9"
      
services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
        command: /start
        restart: always
        image: mitch122/katplan:2432-api-1.0
        container_name: katplan_2432_api
        expose:
            - "9999"
        volumes:
            - ./app/staticfiles:/app/staticfiles:ro
            - ./app/mediafiles:/app/mediafiles:ro
            - ./app/backups:/app/backups:ro
        env_file:
            - ./.envs/.django
            - ./.envs/.postgres
        depends_on:
            - postgres
        networks:
            - katplan_2432_nw

    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
        image: mitch122/katplan:2432-db-1.0
        container_name: katplan_2432_db
        restart: always
        volumes:
            - ./app/postgres:/var/lib/postgresql/data
        env_file:
            - ./.envs/.postgres
        networks:
            - katplan_2432_nw

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        image: mitch122/katplan:2432-nginx-1.0
        container_name: katplan_2432_nginx
        restart: always
        volumes:
            - ./app/staticfiles:/app/staticfiles:ro
            - ./app/mediafiles:/app/mediafiles:ro
        ports:
            - '5000:80'
        depends_on:
            - api
        networks:
            - katplan_2432_nw

networks:
    katplan_2432_nw:
        external: true
